---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2023/4/13 14:34
---

data:extend(
        {
            {
                type = "item",
                name = "kscp-furnaces-4",
                icon = "__base__/graphics/icons/electric-furnace.png",
                icon_size = 64,
                icon_mipmaps = 1,
                subgroup = "extraction-machine",
                place_result = "kscp-furnaces-4",
                stack_size = 32
            },
        }
)