---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2023/4/13 14:34
---
---
local furnaces4 =
{
    {"assembling-machine-3", 5},
    {"processing-unit", 35},
    {"beacon", 1},
    {"concrete", 350},
}

data:extend({

    type = "recipe",
    name = "kscp-furnaces-4",
    ingredients = furnaces4,
    result = "kscp-furnaces-4",
    energy_required = 5,
    enabled = false

})