---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/4/13 22:40
---



data:extend({
    {
        type = "item",
        name = "steel-wall",
        icon = "__ksptooi-server-commons-preprocess__/modules/steel-wall/res/wall.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "defensive-structure",
        order = "a[stone-wall]-a[stone-wall]",
        place_result = "steel-wall",
        stack_size = 100
    }
})