---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/4/13 22:41
---

data:extend({
    {
        type = "recipe",
        name = "steel-wall",
        enabled = false,
        ingredients = {
            {"stone-wall", 1},
            {"steel-plate", 6},
        },
        result = "steel-wall"
    }
})