---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/4/13 22:41
---

data:extend({
    {
        type = "technology",
        name = "steel-wall",
        icon_size = 256, icon_mipmaps = 4,
        icon = "__ksptooi-server-commons-preprocess__/modules/steel-wall/res/stone-wall.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = "steel-wall"
            }
        },
        unit =
        {
            count = 10,
            ingredients = {{"automation-science-pack", 1}},
            time = 10
        },
        order = "a-k-a"
    }
})