---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2023/4/13 17:41
---

local function spawnEnemies(surface, position, evolutionFactor)

    local biterCount = math.random(2, 10)
    local spitterCount = math.random(1, 5)

    local biterType = "small-biter"
    local spitterType = "small-spitter"

    if(evolutionFactor > 0.2) then
        biterType = "small-biter"
        spitterType = "small-spitter"
    end

    if(evolutionFactor > 0.5) then
        biterType = "medium-biter"
        spitterType = "medium-spitter"
    end

    if(evolutionFactor > 0.8) then
        biterType = "big-biter"
        spitterType = "big-spitter"
    end

    if(evolutionFactor > 0.9) then
        biterType = "behemoth-biter"
        spitterType = "behemoth-biter"
    end


    for i=1,biterCount do
        surface.create_entity{name = biterType, position = position, force = "enemy"}
    end

    for i=1,spitterCount do
        surface.create_entity{name = spitterType, position = position, force = "enemy"}
    end

end

local function onEntityDied(event)
    if event.entity.type == "unit-spawner" then
        local evolutionFactor = game.forces["enemy"].evolution_factor
        local position = event.entity.position
        spawnEnemies(event.entity.surface, position, evolutionFactor)
    end
end

script.on_event(defines.events.on_entity_died, onEntityDied)
